[".local/share/fonts/IBMPlexMono"]
    stripComponents = 0
    type = "archive"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.0/IBMPlexMono.zip"
[".local/share/fonts/IosevkaEtoile"]
    type = "archive"
    url = "https://github.com/be5invis/Iosevka/releases/download/v32.3.1/PkgTTC-IosevkaEtoile-32.3.1.zip"
    stripComponents = 0
[[".local/share/fonts/JetBrainsMonoNerd"]
    type = "archive"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/JetBrainsMono.zip"
    stripComponents = 0